package com.sayarti.backend.common.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    RESOURCE_NOT_FOUND,
    BUSINESS_VALIDATION_ERROR,
    DATABASE_ERROR,
    INTERNAL_SERVER_ERROR,
    AUTH_INVALID_CREDENTIALS,
    AUTH_EMAIL_ALREADY_EXISTS,
    AUTH_TOKEN_EXPIRED,
    AUTH_INVALID_TOKEN,
    AUTH_INVALID_REFRESH_TOKEN,
    AUTH_REFRESH_TOKEN_REUSED,
    AUTH_REFRESH_TOKEN_REVOKED,
    AUTH_GOOGLE_LOGIN_FAILED,
    AUTH_ACCOUNT_LINKING_REQUIRED,
    USER_NOT_FOUND,
    VEHICLE_NOT_FOUND,
    VEHICLE_ACCESS_DENIED,
    INVALID_VEHICLE_MILEAGE,
    FUEL_RECORD_NOT_FOUND,
    INVALID_FUEL_RECORD,
    MAINTENANCE_NOT_FOUND,
    EXPENSE_NOT_FOUND,
    REMINDER_NOT_FOUND
}
